name: 'Kuberentes (k8s) cli - kubectl'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'Serhiy Mytrovtsiy <mitrovtsiy@ukr.net>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  args:
    description: 'Arguments for the CLI command'
    required: false
  redirect-to:
    description: 'Variable name to redirect CLI output'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    dest: ${{ inputs.redirect-to }}
